version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/javascript"
    update_schedule: "live"
  - package_manager: "ruby:bundler"
    directory: "/ruby"
    update_schedule: "daily"
